service: metal-archives-api

provider: 
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  profile: ${file(./deploy/config.${self:provider.stage}.js):getEnvVars.AWS_PROFILE}
  environment:
    SCRAPER_URL: ${file(./deploy/config.${self:provider.stage}.js):getEnvVars.SCRAPER_URL}
    MONGODB_URI: ${file(./deploy/config.${self:provider.stage}.js):getEnvVars.MONGODB_URI}
    ELASTICSEARCH_URL: ${file(./deploy/config.${self:provider.stage}.js):getEnvVars.ELASTICSEARCH_URL}
    PORT: ${file(./deploy/config.${self:provider.stage}.js):getEnvVars.PORT}
  iamRoleStatements:
      - Effect: Allow
        Action: "*"
        Resource: "*"

package:
  exclude: 
    - .git/**
    - data/**

functions:

  get-band:
    handler: src/bandHandler.getBand
    memorySize: 128
    description: Get band
    events:
      - http: 
          path: bands/{bandName}/{id}
          method: get
          request:
            parameters: 
               paths: 
                  bandName: true
                  id: true

  get-album:
    handler: src/albumHandler.getAlbum
    memorySize: 128
    description: Get album
    events:
      - http: 
          path: albums/{albumId}
          method: get
          request: 
            parameters: 
               paths: 
                  albumId: true

  search:
    handler: src/searchHandler.search
    memorySize: 128
    description: Search for band or album name
    events:
      - http: 
          path: search/{query}
          method: get
          request: 
            parameters: 
               paths: 
                  query: true
          